gwtbootstrap3/gwtbootstrap3-extras

pom.xml
This is related to https://github.com/gwtbootstrap3/gwtbootstrap3/pull/259.
=> Add gwt-user dependency

pom.xml
As https://github.com/gwtbootstrap3/gwtbootstrap3/pull/256
=> Remove unnecessary resources tag

src/main/resources/org/gwtbootstrap3/extras/respond/Respond.gwt.xml
=> Inherit com.google.gwt.user.Window

src/main/java/org/gwtbootstrap3/extras/select/client/ui/Select.java
Fixes gwtbootstrap3/gwtbootstrap3-extras/issues/52 and gwtbootstrap3/gwtbootstrap3-extras/issues/55
=> Bugfixes for Select

pom.xml
For the idea described in https://github.com/gwtbootstrap3/gwtbootstrap3/pull/261#issuecomment-69798669
=> Set validateOnly to true

src/main/java/org/gwtbootstrap3/extras/datetimepicker/client/ui/base/DateTimePickerBase.java
Sorry for the mistake in the last PR. I'm working on several repos these days.
Extracted DateTimeFormat map to static and removed double bracket initialization.
=> Extracted DateTimeFormat map to static and removed double bracket initialization

src/main/java/org/gwtbootstrap3/extras/bootbox/client/Bootbox.java
Added option to set Bootbox defaults. Added method hideAll().
The defaults are used like this:
```java
Bootbox.createDefaults()
.setLocale("br")
.setBackdrop(false)
.setAnimate(false)
.setDefaults(); //Effectively set the defaults
```
=> Added option to set Bootbox defaults. Added method hideAll().

src/main/java/org/gwtbootstrap3/extras/notify/client/ui/NotifySettings.java
=> Added new notify settings: "newest_on_top"

src/main/java/org/gwtbootstrap3/extras/toggleswitch/client/ui/base/ToggleSwitchBase.java
Also fixed getValue() issue if not attached to DOM
=> fixed again #158 : ValueChangeEvent never fired if not attached to DOM

src/main/java/org/gwtbootstrap3/extras/slider/client/ui/Slider.java
=> Fixed Slider JSNI autoboxing issue

src/main/java/org/gwtbootstrap3/extras/datepicker/client/ui/base/DatePickerBase.java, src/main/java/org/gwtbootstrap3/extras/datetimepicker/client/ui/base/DateTimePickerBase.java
Fixes #164. Added validation support for DatePicker and DateTimePicker.
Fixes #157.  ValueChangeEvent fires when date is onChangeDate event is fired.
Added several inhreitDoc javadoc comments.
=> Added validation support to DatePicker and DateTimePicker.  

pom.xml
Moved snapshot repository declaration to the parent pom.  Added source plugin.
=> Refactoring pom's.

pom.xml, src/main/java/org/gwtbootstrap3/extras/select/client/ui/Select.java
Added selectValues, getOption and getAllSelectedOptions.
=> Allow for selecting values retaining the existing selected values.

src/main/java/org/gwtbootstrap3/extras/slider/client/ui/RangeSlider.java, src/main/java/org/gwtbootstrap3/extras/slider/client/ui/Slider.java, src/main/java/org/gwtbootstrap3/extras/slider/client/ui/base/FormatterCallback.java, src/main/java/org/gwtbootstrap3/extras/slider/client/ui/base/SliderBase.java
Slider formatter should be generic to support both simple and range slider.
=> Range slider formatter needs a JsArrayNumber as argument

src/main/java/org/gwtbootstrap3/extras/fullcalendar/client/ui/DragAndResizeConfig.java
Add the new parameter delta in eventDrop and eventResize as indicated in FullCalendar docs:
http://fullcalendar.io/docs/event_ui/eventResize/
http://fullcalendar.io/docs/event_ui/eventDrop/
=> DragDrop modification as indicated in FullCalendar docs 2.3.1

src/main/java/org/gwtbootstrap3/extras/bootbox/client/Bootbox.java, src/main/java/org/gwtbootstrap3/extras/bootbox/client/callback/ConfirmCallback.java, src/main/java/org/gwtbootstrap3/extras/bootbox/client/callback/PromptCallback.java, src/main/java/org/gwtbootstrap3/extras/bootbox/client/callback/SimpleCallback.java, src/main/java/org/gwtbootstrap3/extras/bootbox/client/options/AlertOptions.java, src/main/java/org/gwtbootstrap3/extras/bootbox/client/options/BootboxLocale.java, src/main/java/org/gwtbootstrap3/extras/bootbox/client/options/BootboxSize.java, src/main/java/org/gwtbootstrap3/extras/bootbox/client/options/ConfirmOptions.java, src/main/java/org/gwtbootstrap3/extras/bootbox/client/options/DialogOptions.java, src/main/java/org/gwtbootstrap3/extras/bootbox/client/options/PromptOptions.java
=> Fully support for bootbox 4.4.0 (Added missing APIs)

src/main/java/org/gwtbootstrap3/extras/toggleswitch/client/ui/base/ToggleSwitchBase.java
Implemented setVisible and isVisible methods for toggle switch
=> fixes #272

src/main/java/org/gwtbootstrap3/extras/select/client/ui/MultipleSelect.java, src/main/java/org/gwtbootstrap3/extras/select/client/ui/Select.java, src/main/java/org/gwtbootstrap3/extras/select/client/ui/SelectBase.java
=> Added method "getSelectedItem(s)" for standard and multiple select.

README.md
=> Fixed API Doc link

src/main/java/org/gwtbootstrap3/extras/datepicker/client/ui/base/DatePickerBase.java
=> Do not manually set/remove focus on text box.

src/main/java/org/gwtbootstrap3/extras/select/client/ui/MultipleSelect.java, src/main/java/org/gwtbootstrap3/extras/select/client/ui/SelectOptions.java
=> Fixed actionsBox typo

src/main/java/org/gwtbootstrap3/extras/select/client/SelectClientBundle.java, src/main/java/org/gwtbootstrap3/extras/select/client/SelectEntryPoint.java
Changed the way to load select JS
=> Trying to fix #308

README.md
Add spaces to README.md so that GitHub would preview Markdown correctly.
=> Add spaces to README.md
